<script setup lang="ts">
import { computed } from 'vue'
import { FileText, CheckCircle, AlertCircle, Calendar } from 'lucide-vue-next'
import { useMeetingStore } from '../stores/meeting'

const meeting = useMeetingStore()

async function retry() {
  meeting.summaryText = ''
  meeting.summaryDone = false
  meeting.status = 'processing'
  await window.electronAPI.meeting.retrySummary()
}

const parsed = computed(() => {
  if (!meeting.summaryDone || !meeting.summaryText) return null
  try {
    // Try to extract JSON from the response (may have markdown fences)
    const jsonMatch = meeting.summaryText.match(/\{[\s\S]*\}/)
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0])
    }
    return null
  } catch {
    return null
  }
})

const hasError = computed(() => parsed.value?.error || (parsed.value && !parsed.value.summary))
</script>

<template>
  <div v-if="meeting.status === 'processing' || meeting.summaryText" class="p-6">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-8 h-8 rounded-lg bg-gradient-to-br from-primary/10 to-purple-500/10 border border-primary/15 flex items-center justify-center">
        <FileText class="w-4 h-4 text-primary" />
      </div>
      <div>
        <h3 class="text-sm font-semibold text-base-content">Meeting Summary</h3>
        <p class="text-[11px] text-base-content/50">Generated by Gemini</p>
      </div>
    </div>

    <!-- Loading state -->
    <div v-if="meeting.status === 'processing' && !meeting.summaryText" class="flex items-center gap-2 text-sm text-base-content/60">
      <span class="loading loading-dots loading-sm"></span>
      Generating summary...
    </div>

    <!-- Streaming text -->
    <div v-if="meeting.summaryText && !parsed" class="border border-base-300 rounded-lg p-4 bg-base-200/50">
      <pre class="text-xs text-base-content/70 whitespace-pre-wrap font-sans">{{ meeting.summaryText }}</pre>
    </div>

    <!-- Error state -->
    <div v-if="hasError" class="border border-red-300 bg-red-50 rounded-lg p-4">
      <div class="flex items-center gap-2 mb-2">
        <AlertCircle class="w-3.5 h-3.5 text-red-500" />
        <span class="text-[11px] uppercase tracking-wider text-red-600 font-medium">Summary Error</span>
      </div>
      <p class="text-xs text-red-700 leading-relaxed">
        {{ parsed?.error || 'Could not generate summary. Check your Gemini API key and quota at ai.dev/rate-limit.' }}
      </p>
      <p class="text-[10px] text-red-500 mt-2">
        Wait ~60s for the rate limit to reset, then click "Generate again" below. Live agents (action items + coach) auto-fall-back to a faster model.
      </p>
      <button
        class="mt-3 text-xs bg-primary text-primary-content px-3 py-1.5 rounded-md hover:opacity-90 transition-opacity"
        @click="retry"
      >
        Generate summary again
      </button>
    </div>

    <!-- Parsed structured summary -->
    <div v-if="parsed && !hasError" class="space-y-4">
      <!-- Summary -->
      <div class="border border-base-300 rounded-lg p-4">
        <div class="text-[11px] uppercase tracking-wider text-base-content/40 mb-2">Summary</div>
        <p class="text-sm text-base-content/80 leading-relaxed">{{ parsed.summary }}</p>
      </div>

      <!-- Key Decisions -->
      <div v-if="parsed.keyDecisions?.length" class="border border-base-300 rounded-lg p-4">
        <div class="flex items-center gap-2 mb-2">
          <CheckCircle class="w-3.5 h-3.5 text-primary" />
          <span class="text-[11px] uppercase tracking-wider text-base-content/40">Key Decisions</span>
        </div>
        <ul class="space-y-1">
          <li v-for="d in parsed.keyDecisions" :key="d" class="text-xs text-base-content/70 flex items-start gap-2">
            <span class="shrink-0 w-1 h-1 rounded-full bg-primary mt-1.5"></span>
            {{ d }}
          </li>
        </ul>
      </div>

      <!-- Action Items -->
      <div v-if="parsed.actionItems?.length" class="border border-primary/20 rounded-lg p-4 bg-primary/[0.02]">
        <div class="flex items-center gap-2 mb-2">
          <AlertCircle class="w-3.5 h-3.5 text-primary" />
          <span class="text-[11px] uppercase tracking-wider text-primary/60">Action Items</span>
        </div>
        <ul class="space-y-2">
          <li v-for="(item, i) in parsed.actionItems" :key="i" class="text-xs text-base-content/80 flex items-start gap-2">
            <svg class="shrink-0 w-3.5 h-3.5 mt-0.5 text-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
              <rect x="3" y="3" width="18" height="18" rx="2" />
            </svg>
            <div>
              <span>{{ item.task }}</span>
              <span v-if="item.assignee" class="ml-1 text-primary/70">({{ item.assignee }})</span>
              <span v-if="item.deadline" class="ml-1 text-base-content/50">by {{ item.deadline }}</span>
            </div>
          </li>
        </ul>
      </div>

      <!-- Follow-ups -->
      <div v-if="parsed.followUps?.length" class="border border-base-300 rounded-lg p-4">
        <div class="flex items-center gap-2 mb-2">
          <Calendar class="w-3.5 h-3.5 text-purple-500" />
          <span class="text-[11px] uppercase tracking-wider text-base-content/40">Follow-ups</span>
        </div>
        <ul class="space-y-1">
          <li v-for="f in parsed.followUps" :key="f" class="text-xs text-base-content/70 flex items-start gap-2">
            <span class="shrink-0 w-1 h-1 rounded-full bg-purple-500 mt-1.5"></span>
            {{ f }}
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
